--- # software installation
- hosts: webservers
  user: ansible
  connection: ssh
  become: yes

  tasks:
    - name: install packages in to webservers
      yum:
        name: docker
        state: present
