--- # creating multiple users
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: creating multiple users
      user: name={{item}} state=present
      with_items: 
        - Sanoop
        - Parvathy
        - Adith
        - Nanda
