--- # My conditional playbook
- name: conditional playbook
  hosts: all
  become: yes
  connection: ssh

  tasks:
    - name: install apache for debian
      command: apt-get insatall apache2 -y
      when: ansible_os_family == "Debian"


    - name: insatll httpd for redhat
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"

